import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';
import 'package:seed/models/loan_agent.dart';
import 'package:seed/models/loan_product.dart';
import 'package:seed/services/loan/loan_repository.dart';
import 'package:seed/services/loan/pdf_generator.dart';
import 'package:seed/services/loan/zip_packager.dart';

enum _GenState { idle, generating, done, error }

class LoanSubmitStep extends StatefulWidget {
  final LoanAgent agent;
  final String userId;
  final String businessId;
  final LoanProduct? selectedProduct;

  const LoanSubmitStep({
    super.key,
    required this.agent,
    required this.userId,
    required this.businessId,
    this.selectedProduct,
  });

  @override
  State<LoanSubmitStep> createState() => _LoanSubmitStepState();
}

class _LoanSubmitStepState extends State<LoanSubmitStep> {
  final _repo = LoanRepository();

  _GenState _state = _GenState.idle;
  String _statusText = '';
  String? _savedZipPath;
  String? _errorMsg;
  Uint8List? _zipBytes;

  final List<String> _steps = [
    'Preparing your documents...',
    'Generating Personal Profile...',
    'Generating Business Profile...',
    'Generating Sales Report...',
    'Generating e-Invoice Summary...',
    'Generating Activity Log...',
    'Packaging into ZIP...',
    'Saving to your device...',
    'Done! Your documents are ready.',
  ];

  @override
  void initState() {
    super.initState();
    _generate();
  }

  Future<void> _generate() async {
    setState(() {
      _state = _GenState.generating;
      _errorMsg = null;
    });
    try {
      _setStatus(0);
      final user = await _repo.fetchUserProfile(widget.userId);
      final business = await _repo.fetchBusinessProfile(widget.businessId);

      _setStatus(1);
      final personalPdf = await PdfGenerator.generatePersonalProfile(user);

      _setStatus(2);
      final businessPdf = await PdfGenerator.generateBusinessProfile(business, user);

      _setStatus(3);
      final salesRows = await _repo.fetchMonthlySales(widget.businessId);
      final salesPdf = await PdfGenerator.generateSalesReport(salesRows);

      _setStatus(4);
      final invoiceRows = await _repo.fetchEInvoices(widget.businessId);
      final invoicePdf = await PdfGenerator.generateEInvoiceSummary(invoiceRows);

      _setStatus(5);
      final activityRows = await _repo.fetchActivityLog(widget.userId);
      final activityPdf = await PdfGenerator.generateActivityLog(activityRows);

      _setStatus(6);
      final now = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());
      final businessName = business['business_name'] ?? 'Unknown Business';
      final readme = '''IMPORTANT NOTICE
----------------
The documents in this package were auto-generated by the SEED platform
based on information provided by the user and recorded business transactions.

These documents are intended as supporting materials for loan application
purposes only. All information should be verified for accuracy before
submission to any financial institution.

SEED and its developers are not responsible for the outcome of any
loan application made using these documents.

Generated: $now
Business: $businessName
''';
      final zipBytes = await createLoanZip({
        'loan_pack/01_personal_profile.pdf': personalPdf,
        'loan_pack/02_business_profile.pdf': businessPdf,
        'loan_pack/03_monthly_sales_report.pdf': salesPdf,
        'loan_pack/04_einvoice_summary.pdf': invoicePdf,
        'loan_pack/05_activity_log.pdf': activityPdf,
        'loan_pack/README.txt': Uint8List.fromList(readme.codeUnits),
      });

      _setStatus(7);
      // Save ZIP directly to device Downloads folder
      await _saveZipToDevice(zipBytes);
      _zipBytes = zipBytes;

      // Record loan request in DB (no file upload)
      final whatsappMsg =
          'Hi ${widget.agent.agentName}, I would like to apply for a loan. '
          'I have attached my Loan Info Pack prepared via SEED. '
          'Please review and advise. Thank you.';
      await _repo.insertLoanRequest(
        agentId: widget.agent.userId,
        microbusinessId: widget.businessId,
        messageTemplate: whatsappMsg,
      );

      _setStatus(8);
      setState(() => _state = _GenState.done);
    } catch (e) {
      if (mounted) {
        setState(() {
          _state = _GenState.error;
          _errorMsg = e.toString();
        });
      }
    }
  }

  void _setStatus(int index) {
    if (mounted) setState(() => _statusText = _steps[index]);
  }

  Future<void> _saveZipToDevice(Uint8List bytes) async {
    try {
      await Permission.storage.request();
    } catch (_) {}

    Directory dir;
    try {
      dir = Directory('/storage/emulated/0/Download');
      if (!await dir.exists()) {
        dir = (await getExternalStorageDirectory()) ??
            await getApplicationDocumentsDirectory();
      }
    } catch (_) {
      dir = await getApplicationDocumentsDirectory();
    }

    final file = File('${dir.path}/loan_pack.zip');
    await file.writeAsBytes(bytes);
    _savedZipPath = file.path;
  }

  Future<void> _downloadZip() async {
    if (_zipBytes == null) return;
    // If already saved during generation, just notify the path
    if (_savedZipPath != null) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('File saved at: $_savedZipPath'),
            duration: const Duration(seconds: 4),
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
      return;
    }
    try {
      // Request storage permission on Android
      final status = await Permission.storage.request();
      if (!status.isGranted && !status.isLimited) {
        // Android 13+ uses different permissions
        final media = await Permission.manageExternalStorage.request();
        if (!media.isGranted) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Storage permission denied. Cannot save file.'),
                behavior: SnackBarBehavior.floating,
              ),
            );
          }
          return;
        }
      }

      // Save to Downloads folder
      Directory? dir;
      try {
        // /storage/emulated/0/Download
        dir = Directory('/storage/emulated/0/Download');
        if (!await dir.exists()) {
          dir = await getExternalStorageDirectory();
        }
      } catch (_) {
        dir = await getApplicationDocumentsDirectory();
      }

      final file = File('${dir!.path}/loan_pack.zip');
      await file.writeAsBytes(_zipBytes!);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Saved to Downloads/loan_pack.zip'),
            duration: const Duration(seconds: 4),
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Download failed: $e'),
                behavior: SnackBarBehavior.floating));
      }
    }
  }

  Future<void> _openWhatsApp() async {
    final number = widget.agent.whatsappNumber.replaceAll('+', '');
    final message = Uri.encodeComponent(
      'Hi ${widget.agent.agentName}, I would like to apply for a loan. '
      'I have attached my Loan Info Pack prepared via SEED. '
      'Please review and advise. Thank you.',
    );
    final url = Uri.parse('https://wa.me/$number?text=$message');
    final launched =
        await launchUrl(url, mode: LaunchMode.externalApplication);
    if (!launched) {
      await Clipboard.setData(
          ClipboardData(text: widget.agent.whatsappNumber));
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
              content: Text('WhatsApp not found. Agent number copied to clipboard.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_state == _GenState.generating) return _buildGenerating();
    if (_state == _GenState.error) return _buildError();
    return _buildSuccess();
  }

  Widget _buildGenerating() {
    return Center(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 40.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(
              width: 64.w,
              height: 64.w,
              child: const CircularProgressIndicator(
                strokeWidth: 3,
                color: Color(0xFF38B6FF),
              ),
            ),
            SizedBox(height: 32.h),
            Text(
              _statusText,
              textAlign: TextAlign.center,
              style: TextStyle(
                  fontSize: 15.sp, fontWeight: FontWeight.w500),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildError() {
    return Center(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 32.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.error_outline, size: 56.sp, color: Colors.red.shade400),
            SizedBox(height: 16.h),
            Text('Generation failed',
                style:
                    TextStyle(fontSize: 16.sp, fontWeight: FontWeight.bold)),
            SizedBox(height: 8.h),
            Text(
              _errorMsg ?? 'Unknown error',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 12.sp, color: Colors.grey),
            ),
            SizedBox(height: 24.h),
            ElevatedButton(
              onPressed: _generate,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.black,
                padding: EdgeInsets.symmetric(horizontal: 32.w, vertical: 14.h),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30.r)),
              ),
              child: const Text('Retry'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSuccess() {
    return SingleChildScrollView(
      padding: EdgeInsets.fromLTRB(20.w, 8.h, 20.w, 32.h),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title
          Row(
            children: [
              Container(
                padding: EdgeInsets.all(10.w),
                decoration: BoxDecoration(
                  color: const Color(0xFF38B6FF).withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(12.r),
                ),
                child: Icon(Icons.download_rounded,
                    size: 22.sp, color: const Color(0xFF38B6FF)),
              ),
              SizedBox(width: 12.w),
              Text(
                'Download the Loan Info Pack',
                style:
                    TextStyle(fontSize: 15.sp, fontWeight: FontWeight.bold),
              ),
            ],
          ),
          SizedBox(height: 16.h),

          // Info pack card
          Container(
            width: double.infinity,
            padding: EdgeInsets.all(20.w),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20.r),
              gradient: const LinearGradient(
                colors: [Color(0xFFB3E5FC), Color(0xFFE8D5F5), Color(0xFFFFE0B2)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Left: contents list
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Contains:',
                          style: TextStyle(
                              fontSize: 13.sp, fontWeight: FontWeight.bold)),
                      SizedBox(height: 8.h),
                      ...[
                        'Business Profile Document',
                        'Monthly Sales Report',
                        'Personal Profile Summary',
                        'e-Invoice Summary',
                        'Activity Log',
                        'README.txt',
                      ].map((item) => Padding(
                            padding: EdgeInsets.only(bottom: 4.h),
                            child: Row(
                              children: [
                                Icon(Icons.check,
                                    size: 12.sp, color: Colors.black87),
                                SizedBox(width: 6.w),
                                Text(item,
                                    style: TextStyle(fontSize: 11.sp)),
                              ],
                            ),
                          )),
                    ],
                  ),
                ),
                SizedBox(width: 12.w),
                // Download button
                GestureDetector(
                  onTap: _downloadZip,
                  child: Container(
                    padding: EdgeInsets.all(10.w),
                    decoration: BoxDecoration(
                      color: Colors.black,
                      borderRadius: BorderRadius.circular(12.r),
                    ),
                    child: Icon(Icons.download_rounded,
                        size: 22.sp, color: Colors.white),
                  ),
                ),
              ],
            ),
          ),
          SizedBox(height: 24.h),

          // Step instructions
          _instructionRow(
            icon: Icons.ads_click,
            iconColor: const Color(0xFF38B6FF),
            text: 'Click the ',
            bold: '"WhatsApp Now" button',
          ),
          SizedBox(height: 14.h),
          _instructionRow(
            icon: Icons.attach_file,
            iconColor: const Color(0xFF38B6FF),
            text: 'When WhatsApp opens, ',
            bold: 'attach the Loan Info Pack',
            trailing: ' before sending the message.',
          ),
          SizedBox(height: 14.h),
          _instructionRow(
            icon: Icons.celebration_outlined,
            iconColor: const Color(0xFF38B6FF),
            text: 'You have now ',
            bold: 'successfully submitted',
            trailing: ' your application!',
          ),
          SizedBox(height: 32.h),

          // WhatsApp button
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              onPressed: _openWhatsApp,
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFF25D366), width: 2),
                padding: EdgeInsets.symmetric(vertical: 16.h),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30.r)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.chat, size: 22.sp, color: const Color(0xFF25D366)),
                  SizedBox(width: 10.w),
                  Text(
                    'Whatsapp Now',
                    style: TextStyle(
                      fontSize: 15.sp,
                      fontWeight: FontWeight.bold,
                      color: const Color(0xFF25D366),
                    ),
                  ),
                ],
              ),
            ),
          ),
          SizedBox(height: 16.h),

          // Disclaimer
          Text(
            'The documents in this package were auto-generated by the SEED platform '
            'based on information provided by the user and recorded business transactions. '
            'These documents are intended as supporting materials for loan application '
            'purposes only. All information should be verified for accuracy before '
            'submission to any financial institution.',
            style: TextStyle(
                fontSize: 10.sp, color: Colors.grey.shade500, height: 1.5),
          ),
        ],
      ),
    );
  }

  Widget _instructionRow({
    required IconData icon,
    required Color iconColor,
    required String text,
    required String bold,
    String trailing = '',
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: EdgeInsets.all(8.w),
          decoration: BoxDecoration(
            color: iconColor.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(10.r),
          ),
          child: Icon(icon, size: 18.sp, color: iconColor),
        ),
        SizedBox(width: 12.w),
        Expanded(
          child: Padding(
            padding: EdgeInsets.only(top: 6.h),
            child: RichText(
              text: TextSpan(
                style: TextStyle(fontSize: 13.sp, color: Colors.black87),
                children: [
                  TextSpan(text: text),
                  TextSpan(
                      text: bold,
                      style:
                          const TextStyle(fontWeight: FontWeight.bold)),
                  TextSpan(text: trailing),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }
}
