import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';
import 'package:seed/models/loan_agent.dart';
import 'package:seed/models/loan_product.dart';
import 'package:seed/services/user_service.dart';
import 'package:seed/services/loan/loan_repository.dart';
import 'package:seed/services/loan/pdf_generator.dart';
import 'package:seed/services/loan/zip_packager.dart';

enum _GenState { idle, generating, done, error }

class LoanSubmitStep extends StatefulWidget {
  final LoanAgent agent;
  final String userId;
  final String businessId;
  final LoanProduct? selectedProduct;

  const LoanSubmitStep({
    super.key,
    required this.agent,
    required this.userId,
    required this.businessId,
    this.selectedProduct,
  });

  @override
  State<LoanSubmitStep> createState() => _LoanSubmitStepState();
}

class _LoanSubmitStepState extends State<LoanSubmitStep> {
  final _repo = LoanRepository();

  _GenState _state = _GenState.idle;
  String _statusText = '';
  String? _savedZipPath;
  String? _errorMsg;
  Uint8List? _zipBytes;

  final List<String> _steps = [
    'Preparing your documents...',
    'Generating Personal Profile...',
    'Generating Business Profile...',
    'Generating Sales Report...',
    'Generating e-Invoice Summary...',
    'Packaging into ZIP...',
    'Saving to your device...',
    'Done! Your documents are ready.',
  ];

  @override
  void initState() {
    super.initState();
    _generate();
  }

  Future<void> _generate() async {
    setState(() {
      _state = _GenState.generating;
      _errorMsg = null;
    });
    try {
      _setStatus(0);
      final user = await _repo.fetchUserProfile(widget.userId);
      final business = await _repo.fetchBusinessProfile(widget.businessId);

      _setStatus(1);
      final personalPdf = await PdfGenerator.generatePersonalProfile(user);

      _setStatus(2);
      final businessPdf = await PdfGenerator.generateBusinessProfile(business, user);

      _setStatus(3);
      final salesRows = await _repo.fetchMonthlySales(widget.businessId);
      final salesPdf = await PdfGenerator.generateSalesReport(salesRows);

      _setStatus(4);
      final invoiceRows = await _repo.fetchEInvoices(widget.businessId);
      final invoicePdf = await PdfGenerator.generateEInvoices(invoiceRows, business);

      _setStatus(5);
      final now = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());
      final businessName = business['business_name'] ?? 'Unknown Business';
      final readme = '''IMPORTANT NOTICE
----------------
The documents in this package were auto-generated by the SEED platform
based on information provided by the user and recorded business transactions.

These documents are intended as supporting materials for loan application
purposes only. All information should be verified for accuracy before
submission to any financial institution.

SEED and its developers are not responsible for the outcome of any
loan application made using these documents.

Generated: $now
Business: $businessName
''';
      final zipBytes = await createLoanZip({
        'loan_pack/01_personal_profile.pdf': personalPdf,
        'loan_pack/02_business_profile.pdf': businessPdf,
        'loan_pack/03_monthly_sales_report.pdf': salesPdf,
        'loan_pack/04_einvoice_summary.pdf': invoicePdf,
        'loan_pack/README.txt': Uint8List.fromList(readme.codeUnits),
      });

      _setStatus(6);
      // Save ZIP directly to device Downloads folder
      await _saveZipToDevice(zipBytes);
      _zipBytes = zipBytes;

      // Record loan request in DB (no file upload)
      final whatsappMsg =
          'Hi ${widget.agent.agentName}, I would like to apply for a loan. '
          'I have attached my Loan Info Pack prepared via SEED. '
          'Please review and advise. Thank you.';
      await _repo.insertLoanRequest(
        agentId: widget.agent.userId,
        microbusinessId: widget.businessId,
        messageTemplate: whatsappMsg,
      );

      _setStatus(7);
      setState(() => _state = _GenState.done);
    } catch (e) {
      if (mounted) {
        setState(() {
          _state = _GenState.error;
          _errorMsg = e.toString();
        });
      }
    }
  }

  void _setStatus(int index) {
    if (mounted) setState(() => _statusText = _steps[index]);
  }

  Future<void> _saveZipToDevice(Uint8List bytes) async {
    try {
      await Permission.storage.request();
    } catch (_) {}

    Directory dir;
    try {
      dir = Directory('/storage/emulated/0/Download');
      if (!await dir.exists()) {
        dir = (await getExternalStorageDirectory()) ??
            await getApplicationDocumentsDirectory();
      }
    } catch (_) {
      dir = await getApplicationDocumentsDirectory();
    }

    final file = File('${dir.path}/loan_pack.zip');
    await file.writeAsBytes(bytes);
    _savedZipPath = file.path;
  }

  Future<void> _downloadZip() async {
    if (_zipBytes == null) return;

    // Show confirmation modal first
    final confirmed = await showModalBottomSheet<bool>(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (_) => _DownloadConfirmSheet(
        fileName: 'loan_pack.zip',
        fileSize: '${(_zipBytes!.lengthInBytes / 1024).toStringAsFixed(1)} KB',
        destination: 'Downloads/loan_pack.zip',
      ),
    );

    if (confirmed != true) return;

    try {
      await Permission.storage.request();

      Directory dir;
      try {
        dir = Directory('/storage/emulated/0/Download');
        if (!await dir.exists()) {
          dir = (await getExternalStorageDirectory()) ??
              await getApplicationDocumentsDirectory();
        }
      } catch (_) {
        dir = await getApplicationDocumentsDirectory();
      }

      final file = File('${dir.path}/loan_pack.zip');
      await file.writeAsBytes(_zipBytes!);
      _savedZipPath = file.path;

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.check_circle, color: Colors.white, size: 18),
                const SizedBox(width: 10),
                const Text('Saved to Downloads/loan_pack.zip'),
              ],
            ),
            backgroundColor: const Color(0xFF43A047),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10.r)),
            duration: const Duration(seconds: 4),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Download failed: $e'),
          backgroundColor: Colors.red[600],
          behavior: SnackBarBehavior.floating,
        ));
      }
    }
  }

  String _buildWhatsAppMessage() {
    final productName = widget.selectedProduct?.service.title ?? 'financial grant';
    final businessName = UserService().currentBusinessName.isNotEmpty
        ? UserService().currentBusinessName
        : UserService().currentOwnerName;

    final templates = {
      'SME Loan': 'Hi, I am $businessName and I am interested in applying for the *SME Loan* programme. '
          'I have prepared my full loan application pack via the SEED platform. '
          'Could you please guide me on the next steps? Thank you.',
      'Microloan': 'Hi, I am $businessName and I would like to apply for the *Microloan* scheme. '
          'I have my business documents ready via SEED. '
          'Please advise on the application process. Thank you.',
      'Grant': 'Hi, I am $businessName and I am applying for a *Business Grant*. '
          'I have gathered all the necessary documents via SEED. '
          'Could you assist me with the submission? Thank you.',
      'BSN Micro': 'Hi, I am $businessName and I am interested in the *BSN Micro Financing* scheme. '
          'I have prepared my loan pack via SEED and would like to proceed with the application. Thank you.',
      'TEKUN': 'Hi, I am $businessName and I would like to apply for *TEKUN Nasional* financing. '
          'My application documents have been prepared via SEED. '
          'Please let me know how to proceed. Thank you.',
      'Agro Bank': 'Hi, I am $businessName and I am applying for *Agro Bank* financing. '
          'I have my full business profile and documents ready via SEED. '
          'Kindly advise on the next steps. Thank you.',
    };

    // Match by keyword in product name
    for (final key in templates.keys) {
      if (productName.toLowerCase().contains(key.toLowerCase())) {
        return templates[key]!;
      }
    }

    // Default fallback
    return 'Hi, I am $businessName and I would like to apply for *$productName*. '
        'I have prepared my full application pack via the SEED platform. '
        'Please advise on the next steps. Thank you.';
  }

  Future<void> _openWhatsApp() async {
    const number = '60109450225'; // MY country code + number
    final message = Uri.encodeComponent(_buildWhatsAppMessage());
    final url = Uri.parse('https://wa.me/$number?text=$message');
    final launched = await launchUrl(url, mode: LaunchMode.externalApplication);
    if (!launched) {
      await Clipboard.setData(const ClipboardData(text: '+60109450225'));
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
              content: Text('WhatsApp not found. Number copied to clipboard.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_state == _GenState.generating) return _buildGenerating();
    if (_state == _GenState.error) return _buildError();
    return _buildSuccess();
  }

  Widget _buildGenerating() {
    return Center(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 40.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(
              width: 64.w,
              height: 64.w,
              child: const CircularProgressIndicator(
                strokeWidth: 3,
                color: Color(0xFF38B6FF),
              ),
            ),
            SizedBox(height: 32.h),
            Text(
              _statusText,
              textAlign: TextAlign.center,
              style: TextStyle(
                  fontSize: 15.sp, fontWeight: FontWeight.w500),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildError() {
    return Center(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 32.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.error_outline, size: 56.sp, color: Colors.red.shade400),
            SizedBox(height: 16.h),
            Text('Generation failed',
                style:
                    TextStyle(fontSize: 16.sp, fontWeight: FontWeight.bold)),
            SizedBox(height: 8.h),
            Text(
              _errorMsg ?? 'Unknown error',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 12.sp, color: Colors.grey),
            ),
            SizedBox(height: 24.h),
            ElevatedButton(
              onPressed: _generate,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.black,
                padding: EdgeInsets.symmetric(horizontal: 32.w, vertical: 14.h),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30.r)),
              ),
              child: const Text('Retry'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSuccess() {
    return SingleChildScrollView(
      padding: EdgeInsets.fromLTRB(20.w, 8.h, 20.w, 32.h),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title
          Row(
            children: [
              Container(
                padding: EdgeInsets.all(10.w),
                decoration: BoxDecoration(
                  color: const Color(0xFF38B6FF).withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(12.r),
                ),
                child: Icon(Icons.download_rounded,
                    size: 22.sp, color: const Color(0xFF38B6FF)),
              ),
              SizedBox(width: 12.w),
              Text(
                'Download the Loan Info Pack',
                style:
                    TextStyle(fontSize: 15.sp, fontWeight: FontWeight.bold),
              ),
            ],
          ),
          SizedBox(height: 16.h),

          // Info pack card
          Container(
            width: double.infinity,
            padding: EdgeInsets.all(20.w),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20.r),
              gradient: const LinearGradient(
                colors: [Color(0xFFB3E5FC), Color(0xFFE8D5F5), Color(0xFFFFE0B2)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Left: contents list
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Contains:',
                          style: TextStyle(
                              fontSize: 13.sp, fontWeight: FontWeight.bold)),
                      SizedBox(height: 8.h),
                      ...[
                        'Business Profile Document',
                        'Monthly Sales Report',
                        'Personal Profile Summary',
                        'e-Invoice Summary',
                        'README.txt',
                      ].map((item) => Padding(
                            padding: EdgeInsets.only(bottom: 4.h),
                            child: Row(
                              children: [
                                Icon(Icons.check,
                                    size: 12.sp, color: Colors.black87),
                                SizedBox(width: 6.w),
                                Text(item,
                                    style: TextStyle(fontSize: 11.sp)),
                              ],
                            ),
                          )),
                    ],
                  ),
                ),
                SizedBox(width: 12.w),
                // Download button
                GestureDetector(
                  onTap: _downloadZip,
                  child: Container(
                    padding: EdgeInsets.all(10.w),
                    decoration: BoxDecoration(
                      color: Colors.black,
                      borderRadius: BorderRadius.circular(12.r),
                    ),
                    child: Icon(Icons.download_rounded,
                        size: 22.sp, color: Colors.white),
                  ),
                ),
              ],
            ),
          ),
          SizedBox(height: 24.h),

          // Step instructions
          _instructionRow(
            icon: Icons.ads_click,
            iconColor: const Color(0xFF38B6FF),
            text: 'Click the ',
            bold: '"WhatsApp Now" button',
          ),
          SizedBox(height: 14.h),
          _instructionRow(
            icon: Icons.attach_file,
            iconColor: const Color(0xFF38B6FF),
            text: 'When WhatsApp opens, ',
            bold: 'attach the Loan Info Pack',
            trailing: ' before sending the message.',
          ),
          SizedBox(height: 14.h),
          _instructionRow(
            icon: Icons.celebration_outlined,
            iconColor: const Color(0xFF38B6FF),
            text: 'You have now ',
            bold: 'successfully submitted',
            trailing: ' your application!',
          ),
          SizedBox(height: 32.h),

          // WhatsApp button
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              onPressed: _openWhatsApp,
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFF25D366), width: 2),
                padding: EdgeInsets.symmetric(vertical: 16.h),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30.r)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.chat, size: 22.sp, color: const Color(0xFF25D366)),
                  SizedBox(width: 10.w),
                  Text(
                    'Whatsapp Now',
                    style: TextStyle(
                      fontSize: 15.sp,
                      fontWeight: FontWeight.bold,
                      color: const Color(0xFF25D366),
                    ),
                  ),
                ],
              ),
            ),
          ),
          SizedBox(height: 16.h),

          // Disclaimer
          Text(
            'The documents in this package were auto-generated by the SEED platform '
            'based on information provided by the user and recorded business transactions. '
            'These documents are intended as supporting materials for loan application '
            'purposes only. All information should be verified for accuracy before '
            'submission to any financial institution.',
            style: TextStyle(
                fontSize: 10.sp, color: Colors.grey.shade500, height: 1.5),
          ),
        ],
      ),
    );
  }

  Widget _instructionRow({
    required IconData icon,
    required Color iconColor,
    required String text,
    required String bold,
    String trailing = '',
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: EdgeInsets.all(8.w),
          decoration: BoxDecoration(
            color: iconColor.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(10.r),
          ),
          child: Icon(icon, size: 18.sp, color: iconColor),
        ),
        SizedBox(width: 12.w),
        Expanded(
          child: Padding(
            padding: EdgeInsets.only(top: 6.h),
            child: RichText(
              text: TextSpan(
                style: TextStyle(fontSize: 13.sp, color: Colors.black87),
                children: [
                  TextSpan(text: text),
                  TextSpan(
                      text: bold,
                      style:
                          const TextStyle(fontWeight: FontWeight.bold)),
                  TextSpan(text: trailing),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }
}

// ── Download confirmation bottom sheet ───────────────────────────────────────
class _DownloadConfirmSheet extends StatelessWidget {
  final String fileName;
  final String fileSize;
  final String destination;

  const _DownloadConfirmSheet({
    required this.fileName,
    required this.fileSize,
    required this.destination,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24.r)),
      ),
      padding: EdgeInsets.fromLTRB(24.w, 16.h, 24.w, 32.h),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle bar
          Container(
            width: 40.w,
            height: 4.h,
            decoration: BoxDecoration(
              color: Colors.grey[300],
              borderRadius: BorderRadius.circular(2.r),
            ),
          ),
          SizedBox(height: 20.h),

          // Icon
          Container(
            width: 64.w,
            height: 64.w,
            decoration: BoxDecoration(
              color: const Color(0xFFE3F2FD),
              borderRadius: BorderRadius.circular(16.r),
            ),
            child: Icon(Icons.download_rounded,
                size: 32.sp, color: const Color(0xFF38B6FF)),
          ),
          SizedBox(height: 16.h),

          Text(
            'Download File',
            style: TextStyle(
                fontSize: 18.sp,
                fontWeight: FontWeight.bold,
                color: const Color(0xFF1A1A1A)),
          ),
          SizedBox(height: 8.h),
          Text(
            'Do you want to save this file to your Downloads folder?',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 13.sp, color: Colors.grey[600]),
          ),
          SizedBox(height: 20.h),

          // File info card
          Container(
            width: double.infinity,
            padding: EdgeInsets.all(16.w),
            decoration: BoxDecoration(
              color: const Color(0xFFF5F7FA),
              borderRadius: BorderRadius.circular(12.r),
            ),
            child: Column(
              children: [
                _infoRow(Icons.folder_zip_outlined, 'File', fileName),
                SizedBox(height: 8.h),
                _infoRow(Icons.data_usage_outlined, 'Size', fileSize),
                SizedBox(height: 8.h),
                _infoRow(Icons.save_alt_outlined, 'Save to', destination),
              ],
            ),
          ),
          SizedBox(height: 24.h),

          // Buttons
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: () => Navigator.pop(context, false),
                  style: OutlinedButton.styleFrom(
                    padding: EdgeInsets.symmetric(vertical: 14.h),
                    side: BorderSide(color: Colors.grey[300]!),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30.r)),
                  ),
                  child: Text('Cancel',
                      style: TextStyle(
                          fontSize: 14.sp, color: Colors.grey[700])),
                ),
              ),
              SizedBox(width: 12.w),
              Expanded(
                child: ElevatedButton(
                  onPressed: () => Navigator.pop(context, true),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF38B6FF),
                    foregroundColor: Colors.white,
                    padding: EdgeInsets.symmetric(vertical: 14.h),
                    elevation: 0,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30.r)),
                  ),
                  child: Text('Download',
                      style: TextStyle(
                          fontSize: 14.sp, fontWeight: FontWeight.w600)),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _infoRow(IconData icon, String label, String value) {
    return Row(
      children: [
        Icon(icon, size: 16.sp, color: const Color(0xFF38B6FF)),
        SizedBox(width: 10.w),
        Text('$label: ',
            style: TextStyle(
                fontSize: 12.sp,
                color: Colors.grey[600],
                fontWeight: FontWeight.w500)),
        Expanded(
          child: Text(value,
              style: TextStyle(
                  fontSize: 12.sp, color: const Color(0xFF1A1A1A)),
              overflow: TextOverflow.ellipsis),
        ),
      ],
    );
  }
}
