import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfGenerator {
  // Cache fonts so we only load them once
  static pw.Font? _regular;
  static pw.Font? _bold;

  static Future<void> _loadFonts() async {
    _regular ??= await PdfGoogleFonts.robotoRegular();
    _bold ??= await PdfGoogleFonts.robotoBold();
  }

  static pw.ThemeData _theme() => pw.ThemeData.withFont(
        base: _regular!,
        bold: _bold!,
      );

  static pw.Widget _buildHeader(String title) {
    return pw.Header(
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('SEED',
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
          pw.Text(title, style: const pw.TextStyle(fontSize: 14)),
          pw.Text(
            DateFormat('d MMMM yyyy').format(DateTime.now()),
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Footer(
      trailing: pw.Text(
        'Generated by SEED Platform - For loan application purposes only. Verify all information before submission.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
      ),
    );
  }

  static pw.Widget _buildInfoTable(List<List<String>> rows) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      children: rows.asMap().entries.map((entry) {
        final isEven = entry.key.isEven;
        final row = entry.value;
        return pw.TableRow(
          decoration: pw.BoxDecoration(
            color: isEven ? PdfColors.grey100 : PdfColors.white,
          ),
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
              child: pw.Text(row[0],
                  style: pw.TextStyle(
                      fontSize: 10, fontWeight: pw.FontWeight.bold)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
              child: pw.Text(row[1],
                  style: const pw.TextStyle(fontSize: 10)),
            ),
          ],
        );
      }).toList(),
    );
  }

  static pw.Widget _buildSectionHeader(String title) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 8, top: 16),
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      decoration: const pw.BoxDecoration(
        color: PdfColors.grey200,
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey800),
      ),
    );
  }

  // Document 1 — Personal Profile Summary
  static Future<Uint8List> generatePersonalProfile(
      Map<String, dynamic> user) async {
    await _loadFonts();
    final doc = pw.Document(theme: _theme());
    doc.addPage(
      pw.MultiPage(
        header: (_) => _buildHeader('Personal Profile Summary'),
        footer: (_) => _buildFooter(),
        build: (context) => [
          _buildSectionHeader('Personal Information'),
          _buildInfoTable([
            ['Full Name', user['name'] ?? '-'],
            ['IC Number', user['ic_number'] ?? '-'],
            ['Date of Birth', user['date_of_birth'] ?? '-'],
            ['Gender', user['gender'] ?? '-'],
            ['Phone Number', user['phone_number'] ?? '-'],
            ['Email Address', user['email'] ?? '-'],
            ['Home Address', user['home_address'] ?? '-'],
          ]),
        ],
      ),
    );
    return doc.save();
  }

  // Document 2 — Business Profile Document
  static Future<Uint8List> generateBusinessProfile(
      Map<String, dynamic> business, Map<String, dynamic> user) async {
    await _loadFonts();
    final doc = pw.Document(theme: _theme());
    doc.addPage(
      pw.MultiPage(
        header: (_) => _buildHeader('Business Profile Document'),
        footer: (_) => _buildFooter(),
        build: (context) => [
          _buildSectionHeader('Business Information'),
          _buildInfoTable([
            ['Business Name', business['business_name'] ?? '-'],
            ['SSM Registration No.', business['ssm_registration_number'] ?? '-'],
            ['Business Type', business['type'] ?? '-'],
            ['Year Established', '${business['year_of_establishment'] ?? '-'}'],
            ['Business Address', business['business_address'] ?? '-'],
            ['Contact Number', business['contact_number'] ?? '-'],
          ]),
          pw.Divider(height: 24),
          _buildSectionHeader('Owner Information'),
          _buildInfoTable([
            ['Owner Name', user['name'] ?? '-'],
            ['IC Number', user['ic_number'] ?? '-'],
            ['Phone Number', user['phone_number'] ?? '-'],
            ['Email Address', user['email'] ?? '-'],
          ]),
        ],
      ),
    );
    return doc.save();
  }

  // Document 3 — Monthly Sales Report
  static Future<Uint8List> generateSalesReport(
      List<Map<String, dynamic>> rows) async {
    await _loadFonts();
    final doc = pw.Document(theme: _theme());
    final fmt = NumberFormat('#,##0.00');

    doc.addPage(
      pw.MultiPage(
        header: (_) => _buildHeader('Monthly Sales Report'),
        footer: (_) => _buildFooter(),
        build: (context) {
          if (rows.isEmpty) {
            return [
              pw.SizedBox(height: 40),
              pw.Center(
                child: pw.Text(
                  'No transaction data available for this period.',
                  style: const pw.TextStyle(
                      fontSize: 12, color: PdfColors.grey600),
                ),
              ),
            ];
          }

          double totalRevenue = 0;
          int totalOrders = 0;
          for (final r in rows) {
            totalRevenue += (r['revenue'] as num).toDouble();
            totalOrders += (r['total_orders'] as int);
          }

          return [
            _buildSectionHeader('Sales Summary — Last 6 Months'),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: ['Month', 'Total Orders', 'Revenue (RM)', 'Avg Order Value (RM)']
                      .map((h) => pw.Padding(
                            padding: const pw.EdgeInsets.all(6),
                            child: pw.Text(h,
                                style: pw.TextStyle(
                                    fontSize: 10,
                                    fontWeight: pw.FontWeight.bold)),
                          ))
                      .toList(),
                ),
                ...rows.asMap().entries.map((entry) {
                  final isEven = entry.key.isEven;
                  final r = entry.value;
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: isEven ? PdfColors.grey100 : PdfColors.white,
                    ),
                    children: [
                      r['month'],
                      '${r['total_orders']}',
                      'RM ${fmt.format((r['revenue'] as num).toDouble())}',
                      'RM ${fmt.format((r['avg_order_value'] as num).toDouble())}',
                    ]
                        .map((v) => pw.Padding(
                              padding: const pw.EdgeInsets.all(6),
                              child: pw.Text(v,
                                  style: const pw.TextStyle(fontSize: 10)),
                            ))
                        .toList(),
                  );
                }),
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    'TOTAL',
                    '$totalOrders',
                    'RM ${fmt.format(totalRevenue)}',
                    '',
                  ]
                      .map((v) => pw.Padding(
                            padding: const pw.EdgeInsets.all(6),
                            child: pw.Text(v,
                                style: pw.TextStyle(
                                    fontSize: 10,
                                    fontWeight: pw.FontWeight.bold)),
                          ))
                      .toList(),
                ),
              ],
            ),
          ];
        },
      ),
    );
    return doc.save();
  }

  // Document 4 — e-Invoice Summary
  static Future<Uint8List> generateEInvoiceSummary(
      List<Map<String, dynamic>> rows) async {
    await _loadFonts();
    final doc = pw.Document(theme: _theme());
    final fmt = NumberFormat('#,##0.00');
    final dateFmt = DateFormat('dd/MM/yyyy');

    doc.addPage(
      pw.MultiPage(
        header: (_) => _buildHeader('e-Invoice Summary'),
        footer: (_) => _buildFooter(),
        build: (context) {
          if (rows.isEmpty) {
            return [
              pw.SizedBox(height: 40),
              pw.Center(
                child: pw.Text(
                  'No transaction data available for this period.',
                  style: const pw.TextStyle(
                      fontSize: 12, color: PdfColors.grey600),
                ),
              ),
            ];
          }

          double grandTotal = 0;
          for (final r in rows) {
            grandTotal += (r['total_amount'] as num).toDouble();
          }

          return [
            _buildSectionHeader('e-Invoice Summary — Last 3 Months'),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(1),
                3: const pw.FlexColumnWidth(2),
                4: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: ['Invoice ID', 'Date', 'Items', 'Amount (RM)', 'Status']
                      .map((h) => pw.Padding(
                            padding: const pw.EdgeInsets.all(6),
                            child: pw.Text(h,
                                style: pw.TextStyle(
                                    fontSize: 9,
                                    fontWeight: pw.FontWeight.bold)),
                          ))
                      .toList(),
                ),
                ...rows.asMap().entries.map((entry) {
                  final isEven = entry.key.isEven;
                  final r = entry.value;
                  final id = (r['id'] as String).substring(0, 8).toUpperCase();
                  final date = dateFmt
                      .format(DateTime.parse(r['created_at'] as String));
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: isEven ? PdfColors.grey100 : PdfColors.white,
                    ),
                    children: [
                      id,
                      date,
                      '${r['item_count']}',
                      'RM ${fmt.format((r['total_amount'] as num).toDouble())}',
                      '${r['transaction_status'] ?? '-'}',
                    ]
                        .map((v) => pw.Padding(
                              padding: const pw.EdgeInsets.all(6),
                              child: pw.Text(v,
                                  style: const pw.TextStyle(fontSize: 9)),
                            ))
                        .toList(),
                  );
                }),
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    'GRAND TOTAL', '', '',
                    'RM ${fmt.format(grandTotal)}', '',
                  ]
                      .map((v) => pw.Padding(
                            padding: const pw.EdgeInsets.all(6),
                            child: pw.Text(v,
                                style: pw.TextStyle(
                                    fontSize: 9,
                                    fontWeight: pw.FontWeight.bold)),
                          ))
                      .toList(),
                ),
              ],
            ),
          ];
        },
      ),
    );
    return doc.save();
  }

  // Document 5 — Activity Log
  static Future<Uint8List> generateActivityLog(
      List<Map<String, dynamic>> rows) async {
    await _loadFonts();
    final doc = pw.Document(theme: _theme());
    final dateFmt = DateFormat('dd/MM/yyyy HH:mm');

    doc.addPage(
      pw.MultiPage(
        header: (_) => _buildHeader('Activity Log'),
        footer: (_) => _buildFooter(),
        build: (context) {
          if (rows.isEmpty) {
            return [
              pw.SizedBox(height: 40),
              pw.Center(
                child: pw.Text(
                  'No activity recorded for this period.',
                  style: const pw.TextStyle(
                      fontSize: 12, color: PdfColors.grey600),
                ),
              ),
            ];
          }

          return [
            _buildSectionHeader('Activity Log — Last 3 Months'),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2.5),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(2),
                3: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: ['Timestamp', 'Action', 'Resource', 'Duration (s)']
                      .map((h) => pw.Padding(
                            padding: const pw.EdgeInsets.all(6),
                            child: pw.Text(h,
                                style: pw.TextStyle(
                                    fontSize: 9,
                                    fontWeight: pw.FontWeight.bold)),
                          ))
                      .toList(),
                ),
                ...rows.asMap().entries.map((entry) {
                  final isEven = entry.key.isEven;
                  final r = entry.value;
                  String ts = '-';
                  try {
                    ts = dateFmt.format(DateTime.parse(r['timestamp'] as String));
                  } catch (_) {}
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: isEven ? PdfColors.grey100 : PdfColors.white,
                    ),
                    children: [
                      ts,
                      '${r['action'] ?? '-'}',
                      '${r['resource_type'] ?? '-'}',
                      '${r['duration_seconds'] ?? '-'}',
                    ]
                        .map((v) => pw.Padding(
                              padding: const pw.EdgeInsets.all(6),
                              child: pw.Text(v,
                                  style: const pw.TextStyle(fontSize: 9)),
                            ))
                        .toList(),
                  );
                }),
              ],
            ),
          ];
        },
      ),
    );
    return doc.save();
  }
}
